version: '3'
services:
  db:
    image: mysql:8.0.19
    volumes:
     - ./data/scripts:/docker-entrypoint-initdb.d
     - ./data/files:/var/lib/mysql-files
    environment:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: spot
        MYSQL_USER: user
        MYSQL_PASSWORD: password
    ports:
       - "3306:3306"
    networks:
      - spot-network
    restart: always
    command:
      - '--character-set-server=utf8mb4'
      - '--secure-file-priv=/var/lib/mysql-files'
      - '--default-authentication-plugin=mysql_native_password'

  api:
    image: pcourbin/spot_api:0.1.0
    build: ./api/SPOTAPI
    environment:
        DATABASE_URL: "mysql://user:password@db:3306/spot"
        PORT: "4000"
    ports:
      - 4000:4000
    networks:
      - spot-network
    depends_on:
      - db
    restart: always

  dbadmin:
    image: phpmyadmin/phpmyadmin:edge-4.9
    environment:
        #PMA_ARBITRARY: 1
        PMA_HOST: db
        MPA_PORT: 3306
        PMA_USER: user
        PMA_PASSWORD: password
    ports:
       - "5000:80"
    networks:
      - spot-network

networks:
  spot-network:
    external: true